source :rubygems

gem "middleman", "~>3.0.5"
gem "middleman-favicon-maker"
gem "middleman-livereload"
gem "susy", "~>1.0.5"
gem "redcarpet"
gem 'ejs'
gem 'luca'
gem 'coffee-filter' # Coffeescript filter for HAML
